apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-container
  template:
    metadata:
      labels:
        app: my-python-container
    spec:
      containers:
      - name: my-python-container
        image: my-python-container:latest
        imagePullPolicy: Never

